-- ================================================================================
-- 1. TABLAS DE CATÁLOGOS Y DICCIONARIOS (Sin dependencias)
-- ================================================================================

CREATE TABLE estado_ticket
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion       TEXT NOT NULL UNIQUE,
    cod_estado_ticket TEXT NOT NULL UNIQUE
);

CREATE TABLE tipo_ticket
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_tipo_ticket TEXT NOT NULL UNIQUE,
    descripcion     TEXT NOT NULL UNIQUE
);

CREATE TABLE niveles_prioridad
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion TEXT NOT NULL UNIQUE
);

CREATE TABLE estado_traslado
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_traslado TEXT NOT NULL UNIQUE,
    descripcion  TEXT NOT NULL UNIQUE
);

CREATE TABLE tipo_tecnico
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion TEXT NOT NULL UNIQUE
);

CREATE TABLE departamentos_soporte
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion      TEXT NOT NULL UNIQUE,
    cod_departamento TEXT NOT NULL UNIQUE
);

CREATE TABLE motivos_pausa
(
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    motivo_pausa          VARCHAR(255) NOT NULL,
    requiere_autorizacion BOOLEAN DEFAULT TRUE
);

CREATE TABLE tipos_turno
(
    id          SERIAL PRIMARY KEY,
    nombre      VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    estado      BOOLEAN DEFAULT TRUE
);

-- ================================================================================
-- 2. TABLAS INTOCABLES Y ENTIDADES PRINCIPALES (Solicitantes y Técnicos)
-- ================================================================================

CREATE TABLE catalogo_fallas
(
    id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_falla           TEXT               NOT NULL UNIQUE,
    descripcion_falla      TEXT               NOT NULL,
    complejidad            SMALLINT DEFAULT 1 NOT NULL CHECK (complejidad BETWEEN 1 AND 10),
    tiempo_resolucion_estimado INTERVAL,
    requiere_visita_fisica BOOLEAN  DEFAULT TRUE,
    id_departamento        INTEGER REFERENCES departamentos_soporte (id),
    categoria              VARCHAR(100),
    subcategoria           VARCHAR(100)
);
CREATE INDEX idx_catalogo_fallas_id_departamento ON catalogo_fallas (id_departamento);

CREATE TABLE servicio
(
    id                         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edificio                   TEXT    DEFAULT 'SIN ESPECIFICAR',
    piso                       INTEGER DEFAULT 0,
    servicios                  TEXT    DEFAULT 'SIN ESPECIFICAR',
    ubicacion                  TEXT    DEFAULT 'SIN ESPECIFICAR',
    unidades                   TEXT    DEFAULT 'SIN ESPECIFICAR',
    id_nivel_prioridad_default INTEGER DEFAULT 1 REFERENCES niveles_prioridad (id)
);

CREATE TABLE solicitantes
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_servicio     INTEGER REFERENCES servicio (id),
    correo          VARCHAR(100) UNIQUE,
    rut             VARCHAR(10) NOT NULL UNIQUE,
    dv              CHAR(1)     NOT NULL,
    nombre_completo TEXT        NOT NULL,
    anexo           INTEGER,
    estado          BOOLEAN DEFAULT TRUE
);

-- Un índice recomendado ya que ahora buscarás solicitantes por su servicio
CREATE INDEX idx_solicitantes_id_servicio ON solicitantes (id_servicio);

CREATE TABLE tecnicos
(
    id                        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut                       VARCHAR(20) NOT NULL UNIQUE,
    dv                        CHAR(1)     NOT NULL,
    nombre_completo           TEXT        NOT NULL,
    id_departamento           INTEGER REFERENCES departamentos_soporte (id),
    id_tipo_tecnico           INTEGER REFERENCES tipo_tecnico (id),
    activo                    BOOLEAN DEFAULT TRUE,
    en_linea                  BOOLEAN DEFAULT FALSE,
    ultima_actividad          TIMESTAMPTZ,
    turno_iniciado            BOOLEAN DEFAULT FALSE,
    fecha_inicio_turno_actual TIMESTAMPTZ
);
CREATE INDEX idx_tecnicos_id_tipo_tecnico ON tecnicos (id_tipo_tecnico);
CREATE INDEX idx_tecnicos_id_departamento ON tecnicos (id_departamento);
CREATE INDEX idx_tecnicos_actividad ON tecnicos (en_linea, ultima_actividad);
CREATE INDEX idx_tecnicos_turno_iniciado ON tecnicos (turno_iniciado);

-- ================================================================================
-- 3. TABLA CENTRAL: TICKET (Núcleo de la Fase 1)
-- ================================================================================

CREATE TABLE ticket
(
    id                      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nro_ticket              TEXT                                  NOT NULL UNIQUE,
    id_solicitante          INTEGER                               NOT NULL REFERENCES solicitantes (id),
    id_tecnico_asignado     INTEGER REFERENCES tecnicos (id),
    id_servicio             INTEGER REFERENCES servicio (id),
    id_tipo_ticket          INTEGER                               NOT NULL REFERENCES tipo_ticket (id),
    cod_estado_ticket       TEXT                                  NOT NULL REFERENCES estado_ticket (cod_estado_ticket),
    id_nivel_prioridad      INTEGER REFERENCES niveles_prioridad (id),
    id_catalogo_falla       INTEGER REFERENCES catalogo_fallas (id),
    id_departamento_soporte INTEGER REFERENCES departamentos_soporte (id),
    critico                 BOOLEAN     DEFAULT FALSE,
    detalle_falla_reportada TEXT                                  NOT NULL,
    ubicacion_obs           TEXT        DEFAULT 'SIN OBSERVACION' NOT NULL,
    created_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_inicio_trabajo    TIMESTAMPTZ,
    fecha_fin_trabajo       TIMESTAMPTZ
);

CREATE INDEX idx_ticket_id_solicitante ON ticket (id_solicitante);
CREATE INDEX idx_ticket_tecnico_estado ON ticket (id_tecnico_asignado, cod_estado_ticket);
CREATE INDEX idx_ticket_id_catalogo_falla ON ticket (id_catalogo_falla);
CREATE INDEX idx_ticket_detalle_falla_gin ON ticket USING gin (to_tsvector('spanish', detalle_falla_reportada));
CREATE INDEX idx_ticket_cod_estado_ticket ON ticket (cod_estado_ticket);

-- ================================================================================
-- 4. DEPENDENCIAS DEL TICKET (Fase 1 y 2: Trazabilidad, Bitácora, Pausas)
-- ================================================================================

CREATE TABLE trazabilidad_ticket
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket          INTEGER     NOT NULL REFERENCES ticket (id) ON DELETE CASCADE,
    cod_estado_ticket  TEXT        NOT NULL REFERENCES estado_ticket (cod_estado_ticket),
    rut_responsable    VARCHAR(20) NOT NULL,
    fecha_trazabilidad TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_trazabilidad_ticket_id_ticket ON trazabilidad_ticket (id_ticket);
CREATE INDEX idx_trazabilidad_ticket_rut ON trazabilidad_ticket (rut_responsable);

CREATE TABLE bitacora_ticket
(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket      INTEGER     NOT NULL REFERENCES ticket (id) ON DELETE CASCADE,
    rut_autor      VARCHAR(20) NOT NULL,
    comentario     TEXT        NOT NULL,
    fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_bitacora_ticket_id_ticket ON bitacora_ticket (id_ticket);

CREATE TABLE ticket_pausas
(
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket             INTEGER     NOT NULL REFERENCES ticket (id) ON DELETE CASCADE,
    fecha_inicio_pausa    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_fin_pausa       TIMESTAMPTZ,
    id_tecnico_pausa      INTEGER     NOT NULL REFERENCES tecnicos (id),
    estado_pausa          VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado_pausa IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')),
    id_motivo_pausa       INTEGER     NOT NULL REFERENCES motivos_pausa (id),
    id_tecnico_autorizado INTEGER REFERENCES tecnicos (id),
    fecha_resolucion      TIMESTAMPTZ
);
CREATE INDEX idx_ticket_pausas_id_ticket ON ticket_pausas (id_ticket);

CREATE TABLE traspaso_ticket
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket          INTEGER NOT NULL REFERENCES ticket (id) ON DELETE CASCADE,
    id_tecnico_origen  INTEGER NOT NULL REFERENCES tecnicos (id),
    id_tecnico_destino INTEGER NOT NULL REFERENCES tecnicos (id),
    cod_traslado       TEXT    NOT NULL REFERENCES estado_traslado (cod_traslado),
    motivo_solicitud   TEXT    NOT NULL,
    fecha_solicitud    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    motivo_respuesta   TEXT,
    fecha_respuesta    TIMESTAMPTZ
);
CREATE INDEX idx_traspaso_ticket_id_ticket ON traspaso_ticket (id_ticket);

-- ================================================================================
-- 5. AYUDAS Y COLABORACIÓN (Fase 2)
-- ================================================================================

CREATE TABLE solicitudes_ayuda
(
    id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket              INTEGER NOT NULL REFERENCES ticket (id) ON DELETE CASCADE,
    id_tecnico_responsable INTEGER NOT NULL REFERENCES tecnicos (id),
    fecha_solicitud        TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP,
    motivo                 TEXT,
    estado_solicitud       TEXT    NOT NULL DEFAULT 'ABIERTA' CHECK (estado_solicitud IN ('ABIERTA', 'CERRADA', 'CANCELADA'))
);

CREATE TABLE participantes_colaboracion
(
    id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud_ayuda     INTEGER NOT NULL REFERENCES solicitudes_ayuda (id) ON DELETE CASCADE,
    id_tecnico_colaborador INTEGER NOT NULL REFERENCES tecnicos (id),
    fecha_aceptacion       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_fin_ayuda        TIMESTAMPTZ,
    observacion            TEXT
);

-- ================================================================================
-- 6. VALORIZACIÓN (Cierre de ticket - Fase 3)
-- ================================================================================

CREATE TABLE valorizacion
(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket      INTEGER  NOT NULL UNIQUE REFERENCES ticket (id) ON DELETE CASCADE,
    id_tecnico     INTEGER  NOT NULL REFERENCES tecnicos (id),
    id_solicitante INTEGER  NOT NULL REFERENCES solicitantes (id),
    nota           SMALLINT NOT NULL CHECK (nota BETWEEN 1 AND 5),
    comentarios    TEXT,
    created_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ================================================================================
-- 7. EXTRAS (Notificaciones y Turnos con historial)
-- ================================================================================

CREATE TABLE dispositivos_notificacion
(
    id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tecnico             INTEGER NOT NULL REFERENCES tecnicos (id) ON DELETE CASCADE,
    token                  TEXT    NOT NULL UNIQUE,
    plataforma             TEXT    NOT NULL CHECK (plataforma IN ('android', 'ios')),
    activo                 BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion         TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_actividad TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_dispositivos_notificacion_id_tecnico ON dispositivos_notificacion (id_tecnico);

CREATE TABLE configuracion_horarios_turno
(
    id            SERIAL PRIMARY KEY,
    id_tipo_turno INTEGER NOT NULL REFERENCES tipos_turno (id),
    dia_semana    INTEGER NOT NULL,
    hora_inicio   TIME    NOT NULL,
    hora_fin      TIME    NOT NULL
);
CREATE INDEX idx_config_horarios_turno ON configuracion_horarios_turno (id_tipo_turno);

CREATE TABLE tecnico_turno
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tecnico    INTEGER NOT NULL REFERENCES tecnicos (id),
    id_tipo_turno INTEGER NOT NULL REFERENCES tipos_turno (id),
    fecha_inicio  DATE    NOT NULL DEFAULT CURRENT_DATE,
    fecha_fin     DATE,
    estado        BOOLEAN          DEFAULT TRUE,
    created_at    TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_tecnico_turno_activo ON tecnico_turno (id_tecnico) WHERE estado = true;

CREATE TABLE historial_jornadas
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tecnico         INTEGER     NOT NULL REFERENCES tecnicos (id) ON DELETE CASCADE,
    fecha_inicio       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_fin          TIMESTAMPTZ,
    minutos_trabajados INT
);
CREATE INDEX idx_historial_jornadas_tecnico ON historial_jornadas (id_tecnico);
