// Code generated by MockGen. DO NOT EDIT.
// Source: soporte/internal/core/ports (interfaces: SolicitanteRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_solicitante_repository.go -package=mocks . SolicitanteRepository

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "soporte/internal/core/domain"
	ports "soporte/internal/core/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockSolicitanteRepository is a mock of SolicitanteRepository interface.
type MockSolicitanteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSolicitanteRepositoryMockRecorder
}

// MockSolicitanteRepositoryMockRecorder is the mock recorder for MockSolicitanteRepository.
type MockSolicitanteRepositoryMockRecorder struct {
	mock *MockSolicitanteRepository
}

// NewMockSolicitanteRepository creates a new mock instance.
func NewMockSolicitanteRepository(ctrl *gomock.Controller) *MockSolicitanteRepository {
	mock := &MockSolicitanteRepository{ctrl: ctrl}
	mock.recorder = &MockSolicitanteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolicitanteRepository) EXPECT() *MockSolicitanteRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSolicitanteRepository) Create(ctx context.Context, solicitante *domain.Solicitante) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, solicitante)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSolicitanteRepositoryMockRecorder) Create(ctx, solicitante any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSolicitanteRepository)(nil).Create), ctx, solicitante)
}

// GetByID mocks base method.
func (m *MockSolicitanteRepository) GetByID(ctx context.Context, id int) (domain.Solicitante, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Solicitante)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSolicitanteRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSolicitanteRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockSolicitanteRepository) List(ctx context.Context, filters ports.ListSolicitantesFilters) ([]domain.Solicitante, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]domain.Solicitante)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSolicitanteRepositoryMockRecorder) List(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSolicitanteRepository)(nil).List), ctx, filters)
}

// Update mocks base method.
func (m *MockSolicitanteRepository) Update(ctx context.Context, solicitante *domain.Solicitante) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, solicitante)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSolicitanteRepositoryMockRecorder) Update(ctx, solicitante any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSolicitanteRepository)(nil).Update), ctx, solicitante)
}
